INSERT INTO Temperatures (TRAIN CHARBON,3,37.4) VALUES ('TER EXPRESS',68,154.4);
INSERT INTO Temperatures (TRAIN CHARBON,3,37.4) VALUES ('TER EXPRESS','NULL','NULL');
INSERT INTO Temperatures (TRAIN CHARBON,3,37.4) VALUES ('TRAIN CHARBON',82,179.6);
INSERT INTO Temperatures (TRAIN CHARBON,3,37.4) VALUES ('TRAIN CHARBON','NULL','NULL');
